### ISSUE TITLE
False Positive from `.findOne()` using Sequelize

### ISSUE THREAD

**Issue by bleow** [ajinabraham/njsscan#114]
I am getting the following vulnerability flagged:

> node_nosqli_injection
> Untrusted user input in findOne() function can result in NoSQL Injection.

in the following snippet of my code:
```
const User = require('#models').user
const Role = require('#models').role
const { validate: uuidValidate } = require('uuid')
const tokenData = res.locals.user

const role = await Role.findOne({
    raw: true,
    include: {
      model: User,
      where: {
        id: uuidValidate(tokenData.id) ? tokenData.id : null
      }
    }
  })
```

For reference, here is role.js
```
module.exports = (sequelize, DataTypes) => {
  const Role = sequelize.define(
    'role',
    {
       id: {
       ....
       },
       name: {
       ....
       },
       ...
    },
)
```

As seen from my code, it uses the `.findOne()` function from `sequelize` ([docs](https://sequelize.org/docs/v6/core-concepts/model-querying-finders/#findone)). 

I believe this flag is a false-positive, since:
- Using sequelize functions largely prevents SQL attacks ([source](https://stackoverflow.com/questions/35668651/how-to-prevent-sql-injection-in-nodejs-and-sequelize) [2](https://stackoverflow.com/questions/69319118/i-need-to-know-about-prevent-sql-injection-on-nodejs-sequelize-orm) [3](https://stackoverflow.com/questions/67057309/sequelize-sql-injection-in-findone))
- My database is SQL-based, so it should not have noSQL vulnerability attacks flagged out.

Looking at the njsscan source code, this issue was flagged out by `njsscan/rules/semantic_grep/database/nosql_find_injection.yaml` ([link](https://github.com/ajinabraham/njsscan/blob/40ff09e58a9fe1dd9d46099a0ff9f6977798fe37/njsscan/rules/semantic_grep/database/nosql_find_injection.yaml)), which does a simple pattern matching for `.findOne()` and its variants.

Perhaps an extra pattern check should be added for code using/importing `sequelize`, to prevent false positives arising from this rule?

**Comment by ajinabraham** [comment]
Thanks for the report and the PR. This should be merged now.

**Comment by maxalmonte14** [comment]
I've been into a rabbit hole since GitLab's pipeline started failing last week at work, it seems this is the cause. We are using TypeORM (which also exposes a `findOne` method) and Postgres, so there's no way a "NoSQL" injection attack is possible, same as with Sequelize.

@ajinabraham I really don't support jumping into a issue and demanding stuff from a maintainer but is it possible to look into this? I'm not familiar with the library (it was already in place when I started working on the project) but I'd gladly take a look and see if I can implement a similar fix so people using TypeORM and njsscan don't run into this.

Thanks in advance.

**Comment by ajinabraham** [comment]
If you can share a code snippet with imports and such triggering this false positive, I can add it to the ruleset.
