### ISSUE TITLE
CWE-79 metadata inconsistency

### ISSUE THREAD

**Issue by zricethezav** [ajinabraham/njsscan#75]
Hi @ajinabraham,

We recently bumped Gitlab's SAST Nodejs-Scan analyzer to 0.2.8 and noticed that CWE-79 was producing different CWE metadata format depending on the rule. One of them has a colon, the other does not:

```
CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')Untrusted User Input in Response will result in Reflected Cross Site Scripting Vulnerability.
```
vs
```
CWE-79 Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')The Pug.js/Jade.js template has an unescaped variable. Untrusted user input passed to this variable results in Cross Site Scripting (XSS).
```

I below this can be attributed to https://github.com/ajinabraham/njsscan/pull/64

See https://gitlab.com/gitlab-org/security-products/analyzers/nodejs-scan/-/merge_requests/104#note_652278582 for more discussion

**Comment by ajinabraham** [comment]
@zricethezav This is because pug.js rule is a pattern matcher [rule](https://github.com/ajinabraham/njsscan/blob/4580dc2c32a6d527f20df4da04be6c1d3b02a85a/njsscan/rules/pattern_matcher/template_rules.yaml#L32) that fetch the cwe information from libsast standards [mapping](https://github.com/ajinabraham/libsast/blob/master/libsast/standards/cwe.yaml) and the other one is a semgrep [rule](https://github.com/ajinabraham/njsscan/blob/4580dc2c32a6d527f20df4da04be6c1d3b02a85a/njsscan/rules/semantic_grep/xss/xss_node.yaml#L135) that has cwe metadata defined explicitly. I am working on making semgrep rules fetch cwe information from libsast that these discrepancies will go away.

**Comment by squaresurf** [comment]
> I am working on making semgrep rules fetch cwe information from libsast that these discrepancies will go away.

@ajinabraham, should we expect cwe rules to be missing the colon from time to time while you're in transition to using libsast?

**Comment by ajinabraham** [comment]
Yes, it will be missing colon for these 9 rules 
https://github.com/ajinabraham/njsscan/blob/4580dc2c32a6d527f20df4da04be6c1d3b02a85a/njsscan/rules/pattern_matcher/template_rules.yaml,
once the migration is done, none of the cwe meta will have a colon

**Comment by ajinabraham** [comment]
Fixed in latest release.
